version: 'version'

services:
  mongodb: 
    image: "mongo"
    volumes: 
      - data:/data/db
    # container_name: mongodb
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: max
    #  MONGO_INITDB_ROOT_PASSWORD : secret
      # - MONGO_INITDB_ROOT_PASSWORD=secret
    env_file:
      - ./env/mongo.env
  backend: 
    # image: "goals-node"
    build: ./backend
    # build:
      # context: ./backend
      # dockerfile: Dockerfile 
      # args:
      #   some-arg:1
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend: 
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    # -it 설정, react-script 버전 최신으로 해서 나는 안해도됨
    # stdin_open: true
    # tty: true
    depends_on:
      - backend    

volumes:
  data:
  logs:
